# Generated by Django 4.2.2 on 2023-06-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_task_delete_todolist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['terminer']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='terminer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
